// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using InstapropAPI.Data;

#nullable disable

namespace InstapropAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030154000_AddPollFlagsAndImage")]
    partial class AddPollFlagsAndImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("InstapropAPI.Models.Poll", b =>
                {
                    b.Property<long>("PollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowChangeVote")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMultipleChoice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowResultsBeforeVote")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("PollId");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("InstapropAPI.Models.PollVote", b =>
                {
                    b.Property<long>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OptionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PollId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoteId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PollId", "AccountId", "OptionIndex")
                        .IsUnique();

                    b.ToTable("PollVotes");
                });
        }
    }
}


