// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyFlipperAPI.Data;

#nullable disable

namespace PropertyFlipperAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112201500_AddLeaderboardTables")]
    partial class AddLeaderboardTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new Snapshot().Build(modelBuilder);
#pragma warning restore 612, 618
        }

        private sealed class Snapshot : AppDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }
    }
}


