// <auto-generated />
using System;
using InstapropAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstapropAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstapropAPI.Models.AIChat", b =>
                {
                    b.Property<Guid>("AIChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPreferences")
                        .HasColumnType("text");

                    b.HasKey("AIChatId");

                    b.HasIndex("UserId");

                    b.ToTable("AIChats");
                });

            modelBuilder.Entity("InstapropAPI.Models.AIChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Options")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MessageId");

                    b.HasIndex("AIChatId");

                    b.ToTable("AIChatMessages");
                });

            modelBuilder.Entity("InstapropAPI.Models.AccountBase", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailVerificationPin")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("EmailVerificationPinExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HashedPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetRequestedEmail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneVerificationPin")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("PhoneVerificationPinExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreviousPhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoleId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SuspensionReason")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalEarnedPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId1");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("AccountType").HasValue("AccountBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InstapropAPI.Models.Auction", b =>
                {
                    b.Property<Guid>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BidCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("AuctionId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("InstapropAPI.Models.Bid", b =>
                {
                    b.Property<Guid>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BidId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("InstapropAPI.Models.Chat", b =>
                {
                    b.Property<Guid>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSupportChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SalesMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SalesMemberId");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("InstapropAPI.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("InstapropAPI.Models.ChildProperty", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BuyingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("BuyingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("CentralAC")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<bool?>("GardenView")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasBalcony")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasBicycleLanes")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasBusinessHub")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasClubhouse")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasCommercialStrip")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasDriverRoom")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGarden")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGenerator")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasInfrastructure")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasJoggingTrail")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasMaidRoom")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasMedicalCenter")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasNannyRoom")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasOutdoorPools")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasPrivatePool")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasRoofAccess")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasStorageRoom")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasUndergroundParking")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("NaturalGas")
                        .HasColumnType("boolean");

                    b.Property<bool?>("NileView")
                        .HasColumnType("boolean");

                    b.Property<string>("Orientation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentPropertyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParkingSlots")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("PyramidView")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool?>("SeaView")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SmartHome")
                        .HasColumnType("boolean");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool?>("StreetView")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ViewType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("PropertyId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentPropertyId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ChildProperties");
                });

            modelBuilder.Entity("InstapropAPI.Models.DeveloperPermission", b =>
                {
                    b.Property<Guid>("DeveloperPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeveloperPermissionId");

                    b.HasIndex("DeveloperId", "FeatureName")
                        .IsUnique();

                    b.ToTable("DeveloperPermissions");
                });

            modelBuilder.Entity("InstapropAPI.Models.DeveloperProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PortfolioDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProfileId");

                    b.HasIndex("AccountId");

                    b.ToTable("DeveloperProfiles");
                });

            modelBuilder.Entity("InstapropAPI.Models.DeveloperRating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RatingType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RatingId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("UserId");

                    b.ToTable("DeveloperRatings");
                });

            modelBuilder.Entity("InstapropAPI.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BidId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReminderSet")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ParentEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RecurrenceCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RecurrenceInterval")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurrencePattern")
                        .HasColumnType("integer");

                    b.Property<int?>("ReminderMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ScheduleBuyingPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ScheduleGroupId")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("InstapropAPI.Models.Faq", b =>
                {
                    b.Property<Guid>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("FaqId");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            FaqId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Answer = "Go to the Add Property screen, fill out the mandatory fields, upload images, and submit for review.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Question = "How do I list a new property?"
                        },
                        new
                        {
                            FaqId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Answer = "Yes, open the property from your dashboard and tap Edit. Changes trigger a short review cycle.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 1, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Question = "Can I edit my property after submission?"
                        },
                        new
                        {
                            FaqId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Answer = "At minimum you need proof of ownership and unit floor plans. Optional docs speed up verification.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 2, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Question = "What documents are required?"
                        },
                        new
                        {
                            FaqId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Answer = "Approved sellers can request an auction. Once approved, buyers place bids until the auction end date.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 3, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            Question = "How do auctions work?"
                        },
                        new
                        {
                            FaqId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Answer = "Pricing leverages market comps, developer data, and our AI valuation engine.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 4, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            Question = "How is property pricing estimated?"
                        },
                        new
                        {
                            FaqId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Answer = "Yes, tap the bookmark icon on any property to store it in your Saved list.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 5, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            Question = "Can I save favourite properties?"
                        },
                        new
                        {
                            FaqId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Answer = "Use the Contact Developer button on the project or property page to open a chat.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 6, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            Question = "How do I contact a developer?"
                        },
                        new
                        {
                            FaqId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Answer = "Our AI Broker suggests opportunities and answers investment questions in real time.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 7, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            Question = "What is the AI Broker?"
                        },
                        new
                        {
                            FaqId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Answer = "Follow projects to receive push notifications and see updates in your feed.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 8, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            Question = "How do I track project updates?"
                        },
                        new
                        {
                            FaqId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Answer = "Tap Forgot Password on the login screen and follow the emailed instructions.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 9, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            Question = "How can I reset my password?"
                        });
                });

            modelBuilder.Entity("InstapropAPI.Models.GoldPrice", b =>
                {
                    b.Property<Guid>("GoldPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerGram")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("GoldPriceId");

                    b.ToTable("GoldPrices");
                });

            modelBuilder.Entity("InstapropAPI.Models.InstallmentSummary", b =>
                {
                    b.Property<Guid>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ContractedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("DownPaymentPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("InstallmentEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFullyPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TermYears")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SummaryId");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("InstallmentSummaries");
                });

            modelBuilder.Entity("InstapropAPI.Models.LeaderboardStanding", b =>
                {
                    b.Property<Guid>("StandingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashbackAwarded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EngagementScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RewardSummary")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<int>("StreakWeeks")
                        .HasColumnType("integer");

                    b.HasKey("StandingId");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("AccountId", "Period");

                    b.HasIndex("Period", "Rank");

                    b.ToTable("LeaderboardStandings");
                });

            modelBuilder.Entity("InstapropAPI.Models.LiveStream", b =>
                {
                    b.Property<Guid>("StreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("integer");

                    b.HasKey("StreamId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("LiveStreams");
                });

            modelBuilder.Entity("InstapropAPI.Models.NewsArticle", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NewsArticleId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("InstapropAPI.Models.NewsImage", b =>
                {
                    b.Property<Guid>("NewsImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uuid");

                    b.HasKey("NewsImageId");

                    b.HasIndex("NewsArticleId");

                    b.ToTable("NewsImages");
                });

            modelBuilder.Entity("InstapropAPI.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BidId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReadByUsers")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Recipients")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InstapropAPI.Models.ParentProperty", b =>
                {
                    b.Property<Guid>("ParentPropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AreaSqm")
                        .HasColumnType("integer");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinishingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasClubhouse")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGarden")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGym")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasParking")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPlayground")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPool")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSecurity")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ParentPropertyId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ParentProperties");
                });

            modelBuilder.Entity("InstapropAPI.Models.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminAccountAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SalesAccountAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserAccountAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId");

                    b.HasIndex("AdminAccountAccountId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("SalesAccountAccountId");

                    b.HasIndex("UserAccountAccountId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("InstapropAPI.Models.ProjectMilestone", b =>
                {
                    b.Property<Guid>("MilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MilestoneId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMilestones");
                });

            modelBuilder.Entity("InstapropAPI.Models.ProjectUpdate", b =>
                {
                    b.Property<Guid>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UpdateId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectUpdates");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyDoc", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeleteUrl")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyDocs");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyImage", b =>
                {
                    b.Property<Guid>("PropertyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteUrl")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsMainImage")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyImageId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyPriceHistory", b =>
                {
                    b.Property<Guid>("PriceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChildPropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ParentPropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PriceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PriceHistoryId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("ChildPropertyId");

                    b.HasIndex("ParentPropertyId");

                    b.ToTable("PropertyPriceHistories");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyValuation", b =>
                {
                    b.Property<Guid>("ValuationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIReasoning")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ComparablesCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MarketTrends")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("PriceRangeHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceRangeLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValuationSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ValuationId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyValuations");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyView", b =>
                {
                    b.Property<Guid>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserLocation")
                        .HasColumnType("text");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ViewId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("PropertyViews");
                });

            modelBuilder.Entity("InstapropAPI.Models.Redemption", b =>
                {
                    b.Property<Guid>("RedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("integer");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RedemptionId");

                    b.HasIndex("AccountId");

                    b.ToTable("Redemptions");
                });

            modelBuilder.Entity("InstapropAPI.Models.Referral", b =>
                {
                    b.Property<Guid>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConverted")
                        .HasColumnType("boolean");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ReferredUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferrerId")
                        .HasColumnType("uuid");

                    b.HasKey("ReferralId");

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.HasIndex("ReferredUserId");

                    b.HasIndex("ReferrerId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("InstapropAPI.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("InstapropAPI.Models.SalesTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TeamId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("SalesTeams");
                });

            modelBuilder.Entity("InstapropAPI.Models.StreamChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StreamId");

                    b.HasIndex("UserId");

                    b.ToTable("StreamChatMessages");
                });

            modelBuilder.Entity("InstapropAPI.Models.StreamViewer", b =>
                {
                    b.Property<Guid>("ViewerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ViewerId");

                    b.HasIndex("UserId");

                    b.HasIndex("StreamId", "UserId")
                        .IsUnique();

                    b.ToTable("StreamViewers");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("AchievementType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AchievementId");

                    b.HasIndex("AccountId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserBadge", b =>
                {
                    b.Property<Guid>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BadgeIcon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("BadgeId");

                    b.HasIndex("AccountId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserDoc", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeleteUrl")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DocId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDocs");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserReward", b =>
                {
                    b.Property<Guid>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RelatedPropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RewardId");

                    b.HasIndex("AccountId");

                    b.ToTable("UserRewards");
                });

            modelBuilder.Entity("InstapropAPI.Models.WeeklyLeaderboardSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HighlightHeadline")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("HighlightSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("PayoutProcessed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SecondPlaceAccountId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SecondPlacePoints")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ThirdPlaceAccountId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ThirdPlacePoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerAccountId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WinnerPoints")
                        .HasColumnType("integer");

                    b.HasKey("SnapshotId");

                    b.HasIndex("PayoutProcessed");

                    b.HasIndex("SecondPlaceAccountId");

                    b.HasIndex("ThirdPlaceAccountId");

                    b.HasIndex("WinnerAccountId");

                    b.HasIndex("WeekStart", "WeekEnd")
                        .IsUnique();

                    b.ToTable("WeeklyLeaderboardSnapshots");
                });

            modelBuilder.Entity("InstapropAPI.Models.AdminAccount", b =>
                {
                    b.HasBaseType("InstapropAPI.Models.AccountBase");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("InstapropAPI.Models.DeveloperAccount", b =>
                {
                    b.HasBaseType("InstapropAPI.Models.AccountBase");

                    b.HasDiscriminator().HasValue("Developer");
                });

            modelBuilder.Entity("InstapropAPI.Models.SalesAccount", b =>
                {
                    b.HasBaseType("InstapropAPI.Models.AccountBase");

                    b.Property<Guid?>("AssignedDeveloperId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SalesTeamId")
                        .HasColumnType("uuid");

                    b.HasIndex("AssignedDeveloperId");

                    b.HasIndex("SalesTeamId");

                    b.HasDiscriminator().HasValue("Sales");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserAccount", b =>
                {
                    b.HasBaseType("InstapropAPI.Models.AccountBase");

                    b.Property<string>("AuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.AIChat", b =>
                {
                    b.HasOne("InstapropAPI.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.AIChatMessage", b =>
                {
                    b.HasOne("InstapropAPI.Models.AIChat", "AIChat")
                        .WithMany("Messages")
                        .HasForeignKey("AIChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIChat");
                });

            modelBuilder.Entity("InstapropAPI.Models.AccountBase", b =>
                {
                    b.HasOne("InstapropAPI.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.Role", null)
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId1");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InstapropAPI.Models.Auction", b =>
                {
                    b.HasOne("InstapropAPI.Models.ChildProperty", "Property")
                        .WithMany("Auctions")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("InstapropAPI.Models.Bid", b =>
                {
                    b.HasOne("InstapropAPI.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.AccountBase", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("InstapropAPI.Models.Chat", b =>
                {
                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.SalesAccount", "SalesMember")
                        .WithMany()
                        .HasForeignKey("SalesMemberId");

                    b.HasOne("InstapropAPI.Models.AccountBase", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");

                    b.Navigation("SalesMember");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.ChatMessage", b =>
                {
                    b.HasOne("InstapropAPI.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.ChildProperty", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.AccountBase", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Property");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("InstapropAPI.Models.ChildProperty", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.ParentProperty", "ParentProperty")
                        .WithMany("ChildProperties")
                        .HasForeignKey("ParentPropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("ParentProperty");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InstapropAPI.Models.DeveloperPermission", b =>
                {
                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("InstapropAPI.Models.DeveloperProfile", b =>
                {
                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("InstapropAPI.Models.DeveloperRating", b =>
                {
                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.Event", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.InstallmentSummary", b =>
                {
                    b.HasOne("InstapropAPI.Models.ChildProperty", "Property")
                        .WithOne("InstallmentSummary")
                        .HasForeignKey("InstapropAPI.Models.InstallmentSummary", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("InstapropAPI.Models.LeaderboardStanding", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.WeeklyLeaderboardSnapshot", "Snapshot")
                        .WithMany("Standings")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("InstapropAPI.Models.LiveStream", b =>
                {
                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("InstapropAPI.Models.NewsArticle", b =>
                {
                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("InstapropAPI.Models.NewsImage", b =>
                {
                    b.HasOne("InstapropAPI.Models.NewsArticle", "NewsArticle")
                        .WithMany("Images")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("InstapropAPI.Models.Notification", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.ParentProperty", b =>
                {
                    b.HasOne("InstapropAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InstapropAPI.Models.Project", b =>
                {
                    b.HasOne("InstapropAPI.Models.AdminAccount", null)
                        .WithMany("Projects")
                        .HasForeignKey("AdminAccountAccountId");

                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "Developer")
                        .WithMany("Projects")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.SalesAccount", null)
                        .WithMany("Projects")
                        .HasForeignKey("SalesAccountAccountId");

                    b.HasOne("InstapropAPI.Models.UserAccount", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserAccountAccountId");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("InstapropAPI.Models.ProjectMilestone", b =>
                {
                    b.HasOne("InstapropAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InstapropAPI.Models.ProjectUpdate", b =>
                {
                    b.HasOne("InstapropAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyDoc", b =>
                {
                    b.HasOne("InstapropAPI.Models.ChildProperty", "Property")
                        .WithMany("PropertyDocs")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyImage", b =>
                {
                    b.HasOne("InstapropAPI.Models.ChildProperty", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyPriceHistory", b =>
                {
                    b.HasOne("InstapropAPI.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.ChildProperty", "ChildProperty")
                        .WithMany()
                        .HasForeignKey("ChildPropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.ParentProperty", "ParentProperty")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ParentPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("ChildProperty");

                    b.Navigation("ParentProperty");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyValuation", b =>
                {
                    b.HasOne("InstapropAPI.Models.ChildProperty", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("InstapropAPI.Models.PropertyView", b =>
                {
                    b.HasOne("InstapropAPI.Models.ChildProperty", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.AccountBase", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.Redemption", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("InstapropAPI.Models.Referral", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "ReferredUser")
                        .WithMany()
                        .HasForeignKey("ReferredUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.AccountBase", "Referrer")
                        .WithMany()
                        .HasForeignKey("ReferrerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferredUser");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("InstapropAPI.Models.SalesTeam", b =>
                {
                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("InstapropAPI.Models.StreamChatMessage", b =>
                {
                    b.HasOne("InstapropAPI.Models.LiveStream", "Stream")
                        .WithMany()
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.AccountBase", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stream");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.StreamViewer", b =>
                {
                    b.HasOne("InstapropAPI.Models.LiveStream", "Stream")
                        .WithMany("Viewers")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InstapropAPI.Models.AccountBase", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserAchievement", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserBadge", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserDoc", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "User")
                        .WithMany("UserDocs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserReward", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("InstapropAPI.Models.WeeklyLeaderboardSnapshot", b =>
                {
                    b.HasOne("InstapropAPI.Models.AccountBase", "SecondPlaceAccount")
                        .WithMany()
                        .HasForeignKey("SecondPlaceAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.AccountBase", "ThirdPlaceAccount")
                        .WithMany()
                        .HasForeignKey("ThirdPlaceAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstapropAPI.Models.AccountBase", "WinnerAccount")
                        .WithMany()
                        .HasForeignKey("WinnerAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SecondPlaceAccount");

                    b.Navigation("ThirdPlaceAccount");

                    b.Navigation("WinnerAccount");
                });

            modelBuilder.Entity("InstapropAPI.Models.SalesAccount", b =>
                {
                    b.HasOne("InstapropAPI.Models.DeveloperAccount", "AssignedDeveloper")
                        .WithMany()
                        .HasForeignKey("AssignedDeveloperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InstapropAPI.Models.SalesTeam", "SalesTeam")
                        .WithMany("SalesMembers")
                        .HasForeignKey("SalesTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedDeveloper");

                    b.Navigation("SalesTeam");
                });

            modelBuilder.Entity("InstapropAPI.Models.AIChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("InstapropAPI.Models.AccountBase", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("UserDocs");
                });

            modelBuilder.Entity("InstapropAPI.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("InstapropAPI.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("InstapropAPI.Models.ChildProperty", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("InstallmentSummary");

                    b.Navigation("PropertyDocs");

                    b.Navigation("PropertyImages");
                });

            modelBuilder.Entity("InstapropAPI.Models.LiveStream", b =>
                {
                    b.Navigation("Viewers");
                });

            modelBuilder.Entity("InstapropAPI.Models.NewsArticle", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("InstapropAPI.Models.ParentProperty", b =>
                {
                    b.Navigation("ChildProperties");

                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("InstapropAPI.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("InstapropAPI.Models.SalesTeam", b =>
                {
                    b.Navigation("SalesMembers");
                });

            modelBuilder.Entity("InstapropAPI.Models.WeeklyLeaderboardSnapshot", b =>
                {
                    b.Navigation("Standings");
                });

            modelBuilder.Entity("InstapropAPI.Models.AdminAccount", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("InstapropAPI.Models.DeveloperAccount", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("InstapropAPI.Models.SalesAccount", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("InstapropAPI.Models.UserAccount", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
